@echo off
echo Running Django backend checks for AgriAsset V21...
C:
cd C:\tools\workspace\AgriAsset_YECO_Enterprise_Final2\backend
echo [1/5] Checking integrity...
python manage.py check
echo [2/5] Migrating database...
python manage.py migrate
echo [3/5] Seeding production data...
python manage.py seed_sardoud_production
echo [4/5] Running Enterprise UAT Cycle...
python manage.py run_enterprise_uat_cycle
echo [5/5] Running Runtime Probe V21...
python manage.py runtime_probe_v21
echo Done!
