import * as fs from 'fs';
import * as crypto from 'crypto';
import * as path from 'path';

// ============================================================================
// AETHER WORLD-CLASS DISTRIBUTED CONSENSUS STORAGE KERNEL (V41.0-FLASH)
// ============================================================================

/**
 * 🕰️ Vector Clock to track logical time across distributed nodes.
 */
export interface VectorClock {
  [nodeId: string]: number;
}

/**
 * 📦 Cryptographically Chained Byzantine Resistant Event
 */
export interface ByzantineEvent {
  eventId: string;
  type: 'WRITE' | 'DELETE';
  timestamp: number;
  nodeId: string;
  vectorClock: VectorClock;
  lamportClock: number;
  payload: {
    key: string;
    value?: string;
  };
  previousHash: string;
  hash: string;
  signature: string; // Cryptographic HEX signature generated by the private key of nodeId
}

/**
 * 🏛️ Bounded Local State Machine State
 */
export interface RuntimeState {
  memoryItems: Record<string, string>;
  lastProcessedClock: VectorClock;
  highestLamportClock: number;
  lastEventHash: string;
  integrityVerified: boolean;
}

/**
 * 📸 Crash-Consistent Snapshot
 */
export interface Snapshot {
  version: number;
  state: RuntimeState;
  lastEventHash: string;
}

/**
 * 📓 Durable Write-Ahead Log (WAL) Entry
 */
export interface WALEntry {
  index: number;
  term: number;
  event: ByzantineEvent;
  checksum: string; // SHA-256 Checksum for Torn-Write Protection
}

/**
 * 🚦 Raft AppendEntries RPC Arguments
 */
export interface AppendEntriesArgs {
  term: number;
  leaderId: string;
  prevLogIndex: number;
  prevLogTerm: number;
  entries: WALEntry[];
  leaderCommit: number;
}

/**
 * 🚦 Raft AppendEntries RPC Result
 */
export interface AppendEntriesResult {
  term: number;
  success: boolean;
}

/**
 * 🚦 Peer Replication Flow Control State
 */
export interface PeerReplicationState {
  matchIndex: number;
  nextIndex: number;
  inFlightRequests: number; // In-Flight append requests tracking for Backpressure
}

/**
 * 🌿 Merkle Tree Node for O(1) Divergence Resolution
 */
export interface MerkleNode {
  hash: string;
  left?: MerkleNode;
  right?: MerkleNode;
}

// ============================================================================
// MERKLE TREE UTILITY BUILDER
// ============================================================================
export class MerkleTreeBuilder {
  /**
   * Generates a Merkle Root Hash from a list of transaction/event hashes.
   * Balances odd-leaf levels by repeating the left leaf.
   */
  public static buildRoot(hashes: string[]): string {
    if (hashes.length === 0) {
      return crypto.createHash('sha256').update('empty_tree').digest('hex');
    }

    let currentLevel = hashes.map(h => ({ hash: h }));

    while (currentLevel.length > 1) {
      const nextLevel: { hash: string }[] = [];
      for (let i = 0; i < currentLevel.length; i += 2) {
        const left = currentLevel[i];
        const right = i + 1 < currentLevel.length ? currentLevel[i + 1] : left;

        const combinedHash = crypto.createHash('sha256')
          .update(left.hash + right.hash)
          .digest('hex');

        nextLevel.push({ hash: combinedHash });
      }
      currentLevel = nextLevel;
    }

    return currentLevel[0].hash;
  }
}

// ============================================================================
// DURABLE WRITE-AHEAD LOG (WAL) ENGINE WITH CRASH CONSISTENCY
// ============================================================================
export class DurableWriteAheadLog {
  private walPath: string;
  private fd: number;

  constructor(walPath: string) {
    this.walPath = walPath;
    const parentDir = path.dirname(walPath);
    if (!fs.existsSync(parentDir)) {
      fs.mkdirSync(parentDir, { recursive: true });
    }
    this.fd = fs.openSync(this.walPath, 'a+');
  }

  /**
   * Calculates SHA-256 checksum for a WAL entry to prevent Torn-Writes
   */
  public calculateChecksum(entry: Omit<WALEntry, 'checksum'>): string {
    const data = `${entry.index}:${entry.term}:${JSON.stringify(entry.event)}`;
    return crypto.createHash('sha256').update(data).digest('hex');
  }

  /**
   * Appends an entry to the WAL file with immediate fsync disk persistence
   */
  public appendEntry(index: number, term: number, event: ByzantineEvent): WALEntry {
    const entryWithoutChecksum: Omit<WALEntry, 'checksum'> = { index, term, event };
    const checksum = this.calculateChecksum(entryWithoutChecksum);
    const entry: WALEntry = { ...entryWithoutChecksum, checksum };

    const serialized = JSON.stringify(entry) + '\n';
    const buffer = Buffer.from(serialized, 'utf8');

    // 1. Sync write to Kernel memory buffer
    fs.writeSync(this.fd, buffer, 0, buffer.length);
    
    // 2. Hardware level fsync to prevent cache loss or interruption crashes
    fs.fsyncSync(this.fd);

    return entry;
  }

  /**
   * Recovers and verifies WAL entries, detecting and throwing on Torn-Writes
   */
  public recoverAllEntries(): WALEntry[] {
    if (!fs.existsSync(this.walPath)) {
      return [];
    }

    const content = fs.readFileSync(this.walPath, 'utf8').trim();
    if (!content) return [];

    const lines = content.split('\n');
    const entries: WALEntry[] = [];

    for (const line of lines) {
      if (!line) continue;
      try {
        const entry = JSON.parse(line) as WALEntry;
        
        // Validate Checksum for Torn-Write Protection
        const expectedChecksum = this.calculateChecksum({
          index: entry.index,
          term: entry.term,
          event: entry.event
        });

        if (entry.checksum !== expectedChecksum) {
          throw new Error(`Torn-Write Detected! Expected ${expectedChecksum}, got ${entry.checksum}`);
        }

        entries.push(entry);
      } catch (e: any) {
        throw new Error(`WAL Frame Corruption: ${e.message || e}`);
      }
    }

    return entries;
  }

  public close(): void {
    fs.closeSync(this.fd);
  }
}

// ============================================================================
// CONCURRENT CONSENSUS RUNTIME KERNEL (THE PLATFORM CORE)
// ============================================================================
export class ProductionConsensusKernel {
  private nodeId: string;
  private currentTerm: number = 0;
  private commitIndex: number = 0;
  private lastAppliedIndex: number = 0;
  
  private log: WALEntry[] = [];
  private stateMachine: RuntimeState;
  
  private peerStates: Record<string, PeerReplicationState> = {};
  private trustedPublicKeys: Record<string, string> = {};
  private totalNodes: number;

  // Adaptive Backpressure Limits
  private readonly MAX_INFLIGHT_APPENDS = 5;

  constructor(
    nodeId: string,
    peerIds: string[],
    trustedPublicKeys: Record<string, string>,
    initialState?: RuntimeState
  ) {
    this.nodeId = nodeId;
    this.trustedPublicKeys = trustedPublicKeys;
    this.totalNodes = peerIds.length + 1;

    for (const peerId of peerIds) {
      this.peerStates[peerId] = { matchIndex: 0, nextIndex: 1, inFlightRequests: 0 };
    }

    this.stateMachine = initialState || {
      memoryItems: {},
      lastProcessedClock: {},
      highestLamportClock: 0,
      lastEventHash: '0'.repeat(64),
      integrityVerified: true
    };

    // Bootstrap local log with Genesis WAL entry
    const genesisEvent: ByzantineEvent = {
      eventId: 'GENESIS_EVENT',
      type: 'WRITE',
      timestamp: 0,
      nodeId: 'GENESIS',
      vectorClock: {},
      lamportClock: 0,
      payload: { key: 'GENESIS', value: 'BOOTSTRAPPED' },
      previousHash: '0'.repeat(64),
      hash: '0'.repeat(64),
      signature: '0'.repeat(64)
    };

    this.log.push({
      index: 0,
      term: 0,
      event: genesisEvent,
      checksum: '0'.repeat(64)
    });
  }

  /**
   * Cryptographically validates public key signature of an event
   */
  public verifyByzantineSignature(event: ByzantineEvent): boolean {
    // If Genesis or bootstrapped Node, allow immediately
    if (event.nodeId === 'GENESIS') return true;

    const publicKeyPEM = this.trustedPublicKeys[event.nodeId];
    if (!publicKeyPEM) {
      return false; // Untrusted Node trying to inject state
    }

    const dataToVerify = JSON.stringify({
      eventId: event.eventId,
      type: event.type,
      timestamp: event.timestamp,
      nodeId: event.nodeId,
      vectorClock: event.vectorClock,
      lamportClock: event.lamportClock,
      payload: event.payload,
      previousHash: event.previousHash,
      hash: event.hash
    });

    try {
      const verifier = crypto.createVerify('sha256');
      verifier.update(dataToVerify);
      return verifier.verify(publicKeyPEM, event.signature, 'hex');
    } catch {
      return false;
    }
  }

  /**
   * Enforces Backpressure flow control by locking inflight append windows
   */
  public acquireReplicationPermit(peerId: string): boolean {
    const peer = this.peerStates[peerId];
    if (!peer) return false;

    if (peer.inFlightRequests >= this.MAX_INFLIGHT_APPENDS) {
      return false; // Backpressure triggered: follower queue full
    }

    peer.inFlightRequests++;
    return true;
  }

  public releaseReplicationPermit(peerId: string): void {
    const peer = this.peerStates[peerId];
    if (peer && peer.inFlightRequests > 0) {
      peer.inFlightRequests--;
    }
  }

  /**
   * Performs an atomic linearizable query (ReadIndex protocol)
   */
  public async executeLinearizableRead(
    queryKey: string,
    confirmLeadershipQuorum: () => Promise<boolean>
  ): Promise<string | undefined> {
    const readIndex = this.commitIndex;

    // Confirm leadership at this exact instant
    const activeLeader = await confirmLeadershipQuorum();
    if (!activeLeader) {
      throw new Error(`Stale Read Blocked: Leadership has expired.`);
    }

    // Wait until local state machine is fully synchronized up to the read barrier index
    while (this.lastAppliedIndex < readIndex) {
      this.applyCommittedEntries();
      await new Promise(resolve => setTimeout(resolve, 1));
    }

    return this.stateMachine.memoryItems[queryKey];
  }

  /**
   * Applies committed entries to the memory state machine sequentially
   */
  public applyCommittedEntries(): number {
    let appliedCount = 0;

    while (this.lastAppliedIndex < this.commitIndex) {
      const nextIndex = this.lastAppliedIndex + 1;
      const entry = this.log[nextIndex];

      if (!entry) break;

      try {
        if (entry.event.eventId !== 'GENESIS_EVENT') {
          const { type, payload } = entry.event;
          if (type === 'WRITE') {
            this.stateMachine.memoryItems[payload.key] = payload.value || '';
          } else if (type === 'DELETE') {
            delete this.stateMachine.memoryItems[payload.key];
          }
        }
      } catch (e) {
        throw new Error(`Fatal Transition Failure: State machine crashed at index ${nextIndex}`);
      }

      this.lastAppliedIndex = nextIndex;
      this.stateMachine.highestLamportClock = Math.max(
        this.stateMachine.highestLamportClock,
        entry.event.lamportClock
      );
      this.stateMachine.lastEventHash = entry.event.hash;
      appliedCount++;
    }

    return appliedCount;
  }

  /**
   * Evaluates leader consensus and commits indexes replicated to a majority quorum
   */
  public updateLeaderCommitIndex(): boolean {
    let advanced = false;

    for (let N = this.commitIndex + 1; N < this.log.length; N++) {
      if (this.log[N].term !== this.currentTerm) {
        continue;
      }

      let ackCount = 1; // Current Leader ack is guaranteed
      for (const peerId in this.peerStates) {
        if (this.peerStates[peerId].matchIndex >= N) {
          ackCount++;
        }
      }

      const majorityQuorum = Math.floor(this.totalNodes / 2) + 1;
      if (ackCount >= majorityQuorum) {
        this.commitIndex = N;
        advanced = true;
      }
    }

    return advanced;
  }

  /**
   * Processes incoming replicate requests (Raft Append-Entries Replicator Loop)
   */
  public appendEntries(args: AppendEntriesArgs): AppendEntriesResult {
    // 1. Term check
    if (args.term < this.currentTerm) {
      return { term: this.currentTerm, success: false };
    }

    if (args.term > this.currentTerm) {
      this.currentTerm = args.term;
    }

    // 2. Log Consistency matching property
    const hasPrevLog = this.log.length > args.prevLogIndex;
    if (!hasPrevLog || this.log[args.prevLogIndex].term !== args.prevLogTerm) {
      return { term: this.currentTerm, success: false };
    }

    // 3. Byzantine authenticity and checksum verify
    for (const entry of args.entries) {
      if (!this.verifyByzantineSignature(entry.event)) {
        throw new Error(`Byzantine Signature Mismatch: Denying entry insertion at index ${entry.index}`);
      }
    }

    // 4. Resolve log divergencies (Truncate mismatch nodes)
    for (const entry of args.entries) {
      const idx = entry.index;
      if (this.log.length > idx) {
        if (this.log[idx].term !== entry.term) {
          this.log = this.log.slice(0, idx); // Truncate divergent logs
          this.log.push(entry);
        }
      } else {
        this.log.push(entry);
      }
    }

    // 5. Update Local Commit Index
    if (args.leaderCommit > this.commitIndex) {
      const lastNewIndex = args.entries.length > 0
        ? args.entries[args.entries.length - 1].index
        : args.prevLogIndex;

      this.commitIndex = Math.min(args.leaderCommit, lastNewIndex);
      this.applyCommittedEntries();
    }

    return { term: this.currentTerm, success: true };
  }

  /**
   * Background Compactor and Segments lifecycle management
   */
  public compactLogs(beforeIndex: number, snapshot: Snapshot): WALEntry[] {
    if (beforeIndex > this.commitIndex) {
      throw new Error(`Compaction Denied: Cannot prune logs beyond verified commitIndex.`);
    }

    // Capture and rotate Genesis Snapshot using fast, high-performance structural shallow copy
    this.stateMachine = {
      memoryItems: { ...snapshot.state.memoryItems },
      lastProcessedClock: { ...snapshot.state.lastProcessedClock },
      highestLamportClock: snapshot.state.highestLamportClock,
      lastEventHash: snapshot.state.lastEventHash,
      integrityVerified: snapshot.state.integrityVerified
    };
    this.lastAppliedIndex = beforeIndex;

    const remainingEntries = this.log.slice(beforeIndex);
    this.log = remainingEntries;

    return this.log;
  }

  // Helper APIs for testing and validation
  public updatePeerState(peerId: string, matchIndex: number): void {
    const peer = this.peerStates[peerId];
    if (peer) {
      peer.matchIndex = matchIndex;
      peer.nextIndex = matchIndex + 1;
      this.releaseReplicationPermit(peerId);

      if (this.updateLeaderCommitIndex()) {
        this.applyCommittedEntries();
      }
    }
  }

  public getCommitIndex(): number {
    return this.commitIndex;
  }

  public getLastAppliedIndex(): number {
    return this.lastAppliedIndex;
  }

  public getMemoryState(): Record<string, string> {
    return { ...this.stateMachine.memoryItems };
  }

  public getLogLength(): number {
    return this.log.length;
  }

  public setTerm(term: number): void {
    this.currentTerm = term;
  }
}
