import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'

export const GOD_MODE_TRANSPILER_TOOL_NAME = 'GodModeTranspilerTool'

const inputSchema = z.strictObject({
  djangoModelCode: z.string().describe('The raw Python source code of the Django model (e.g. models.CharField...)'),
  modelName: z.string().describe('The name of the Model class'),
  targetLang: z.enum(['flutter', 'react']).describe('The target output language (flutter for SIMPLE mode, react for STRICT mode)'),
})

type InputSchema = typeof inputSchema

const outputSchema = z.object({
  success: z.boolean(),
  generatedCode: z.string().describe('The generated UI/Form code'),
  omittedFields: z.array(z.string()).describe('Fields omitted due to policy (e.g. financial fields in SIMPLE mode)'),
})

type Output = z.infer<typeof outputSchema>

export const GodModeTranspilerTool = buildTool({
  name: GOD_MODE_TRANSPILER_TOOL_NAME,
  searchHint: 'transpile and auto-generate flutter dart or react frontend code from django models',
  maxResultSizeChars: 100000,
  shouldDefer: false,
  async description(input) {
    const { modelName, targetLang } = input as { modelName: string, targetLang: string }
    return `The Swarm is transpiling Django model ${modelName} into ${targetLang} UI code.`
  },
  userFacingName() {
    return 'God-Mode Transpiler'
  },
  getActivityDescription(input) {
    return `Transpiling ${(input as { modelName: string }).modelName}`
  },
  get inputSchema(): InputSchema {
    return inputSchema
  },
  get outputSchema(): typeof outputSchema {
    return outputSchema
  },
  isConcurrencySafe() {
    return true
  },
  isReadOnly() {
    return true // As per the Sovereign Council: Generate code, but don't overwrite files directly!
  },
  toAutoClassifierInput(input) {
    return `Transpile ${input.modelName}`
  },
  async checkPermissions(input, context) {
    return {
      behavior: 'allow',
      updatedInput: input,
      decisionReason: { type: 'other', reason: 'Code Generation does not modify files directly.' },
    }
  },
  async prompt(_options) {
    return `Use this tool to generate frontend forms and classes directly from Django Python models. It enforces AgriAsset's SIMPLE/STRICT boundaries.`
  },
  async validateInput(input) {
    return { result: true }
  },
  async call({ djangoModelCode, modelName, targetLang }) {
    console.log(`[God-Mode Transpiler] Analyzing Django Model: ${modelName}`);

    // Parse the Python code roughly using Regex to extract fields
    const fieldRegex = /([a-zA-Z0-9_]+)\s*=\s*models\.([a-zA-Z0-9_]+)/g;
    const fields: { name: string, type: string }[] = [];
    let match;
    while ((match = fieldRegex.exec(djangoModelCode)) !== null) {
      fields.push({ name: match[1], type: match[2] });
    }

    const omittedFields: string[] = [];
    let generatedCode = '';

    if (targetLang === 'flutter') {
      // Flutter SIMPLE Mode Generation Rules
      generatedCode += `// 🚀 Auto-Generated by God-Mode Transpiler\n`;
      generatedCode += `// Model: ${modelName} (SIMPLE Mode Field Form)\n\n`;
      generatedCode += `import 'package:flutter/material.dart';\n\n`;
      generatedCode += `class ${modelName}Form extends StatelessWidget {\n`;
      generatedCode += `  const ${modelName}Form({super.key});\n\n`;
      generatedCode += `  @override\n  Widget build(BuildContext context) {\n`;
      generatedCode += `    return ListView(\n      padding: const EdgeInsets.all(16),\n      children: <Widget>[\n`;

      for (const field of fields) {
        // Enforce Financial Integrity Guardian Rule: The Unbreakable Shield
        const financialKeywords = ['price', 'cost', 'amount', 'revenue', 'margin', 'value', 'budget', 'ledger'];
        const isFinancialField = financialKeywords.some(keyword => field.name.toLowerCase().includes(keyword));

        if (isFinancialField) {
          omittedFields.push(field.name);
          continue; 
        }

        const widgetType = 'TextFormField';
        let keyboardType = 'TextInputType.text';
        
        if (field.type.includes('Decimal') || field.type.includes('Integer')) {
          keyboardType = 'TextInputType.numberWithOptions(decimal: true)';
        }

        generatedCode += `        Padding(\n`;
        generatedCode += `          padding: const EdgeInsets.only(bottom: 12),\n`;
        generatedCode += `          child: ${widgetType}(\n`;
        generatedCode += `            keyboardType: ${keyboardType},\n`;
        generatedCode += `            decoration: const InputDecoration(\n`;
        generatedCode += `              labelText: '${field.name}',\n`;
        generatedCode += `              border: OutlineInputBorder(),\n`;
        generatedCode += `            ),\n`;
        generatedCode += `          ),\n`;
        generatedCode += `        ),\n`;
      }

      generatedCode += `      ],\n    );\n  }\n}\n`;

    } else if (targetLang === 'react') {
      // React STRICT Mode Generation
      generatedCode += `// 🚀 Auto-Generated by God-Mode Transpiler\n`;
      generatedCode += `// Model: ${modelName} (STRICT Mode Admin Dashboard)\n\n`;
      generatedCode += `import React from 'react';\n\n`;
      generatedCode += `export const ${modelName}Dashboard = () => {\n`;
      generatedCode += `  return (\n    <div className="p-4">\n      <h1 className="font-bold text-xl">${modelName} Control</h1>\n      <form className="mt-4 flex flex-col gap-4">\n`;

      for (const field of fields) {
        generatedCode += `        <div className="flex flex-col">\n`;
        generatedCode += `          <label className="text-sm font-medium text-gray-700">${field.name}</label>\n`;
        generatedCode += `          <input type="${field.type.includes('Decimal') ? 'number' : 'text'}" className="border p-2 rounded mt-1" />\n`;
        generatedCode += `        </div>\n`;
      }

      generatedCode += `      </form>\n    </div>\n  );\n};\n`;
    }

    return {
      data: {
        success: true,
        generatedCode,
        omittedFields,
      }
    }
  },
  mapToolResultToToolResultBlockParam({ generatedCode, omittedFields }, toolUseID) {
    let msg = generatedCode;
    if (omittedFields.length > 0) {
      msg = `// [SECURITY NOTICE] Omitted Fields: ${omittedFields.join(', ')}\n\n` + msg;
    }
    return {
      tool_use_id: toolUseID,
      type: 'tool_result',
      content: msg,
    }
  },
} satisfies ToolDef<InputSchema, Output>)
