import os
import re
import datetime

# --- SOVEREIGN DISTILLED AUDIT V15.0-APEX ---
PROJECT_ROOT = r"c:\tools\workspace\AgriAsset_YECO_Enterprise_Final2"
REPORT_PATH = os.path.join(PROJECT_ROOT, "DISTILLED_QUALITY_REPORT.md")

class DistilledAuditor:
    def __init__(self):
        self.results = {
            "logic_purity": [],
            "fiscal_integrity": [],
            "ux_aesthetics": [],
            "documentation": []
        }
        self.files_scanned = 0

    def scan_project(self):
        for root, dirs, files in os.walk(PROJECT_ROOT):
            if any(x in root for x in [".git", "node_modules", "venv", "__pycache__", "dist"]):
                continue
            
            for file in files:
                f_path = os.path.join(root, file)
                self.files_scanned += 1
                
                if file.endswith(".py"):
                    self.audit_python(f_path)
                elif file.endswith((".jsx", ".tsx", ".js")):
                    self.audit_frontend(f_path)

    def audit_python(self, path):
        # Axis 4: Documentation (Check first)
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
            lines = content.splitlines()
            if len(lines) > 20 and '"""' not in content:
                self.results["documentation"].append(f"Missing Docstrings in {os.path.basename(path)}")

        # Skip further audit for tests and third-party-like scripts
        if "test_" in path or "conftest.py" in path or "site-packages" in path:
            return

        # Axis 1: Logic Purity (Dead Code / Unused)
        # Search for TODO/FIXME in comments only
        if re.search(r"#.*(TODO|FIXME)", content):
            self.results["logic_purity"].append(f"Technical Debt found in {os.path.basename(path)}")
        
        # Axis 2: Fiscal Integrity
        # Catch models.FloatField() or FloatField() assignment
        if re.search(r"=\s*models\.FloatField", content) or re.search(r"field\s*=\s*FloatField", content):
            self.results["fiscal_integrity"].append(f"Anti-Pattern: FloatField in {os.path.basename(path)}")
        
        # Catch raw division / if not protected by Decimal context
        if "/ " in content and "Decimal" not in content and "math." not in content:
             self.results["fiscal_integrity"].append(f"Risk: Raw division detected in {os.path.basename(path)}")

    def audit_frontend(self, path):
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
            # Axis 3: UX Aesthetics
            if "framer-motion" not in content and "animate" in content.lower():
                self.results["ux_aesthetics"].append(f"Legacy Animation in {os.path.basename(path)} (Suggest Framer Motion)")
            if "className=" in content and "tailwind-merge" not in content and "twMerge" not in content:
                 self.results["ux_aesthetics"].append(f"CSS Conflict Risk in {os.path.basename(path)} (Missing tailwind-merge)")

    def generate_report(self):
        with open(REPORT_PATH, "w", encoding="utf-8") as f:
            f.write("# 💎 Sovereign Distilled Quality Report (V15.0)\n")
            f.write(f"> **آخر فحص مقطر:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"> **إجمالي الملفات المفحوصة:** {self.files_scanned}\n\n")
            
            f.write("## 🧬 مصفوفة الجودة (Quality Matrix)\n")
            f.write("```mermaid\npie title نقاط القوة والضعف\n")
            f.write(f'  "نقاء المنطق" : {100 - len(self.results["logic_purity"])}\n')
            f.write(f'  "النزاهة المالية" : {100 - len(self.results["fiscal_integrity"])}\n')
            f.write(f'  "جماليات UX" : {100 - len(self.results["ux_aesthetics"])}\n')
            f.write(f'  "التوثيق السيادي" : {100 - len(self.results["documentation"])}\n')
            f.write("```\n\n")

            sections = {
                "🔴 نقاء المنطق": "logic_purity",
                "💰 النزاهة المالية (GRP)": "fiscal_integrity",
                "🎨 جماليات واجهة المستخدم (Apex)": "ux_aesthetics",
                "📚 التوثيق والمعايير": "documentation"
            }

            for title, key in sections.items():
                f.write(f"### {title}\n")
                if not self.results[key]:
                    f.write("- ✅ لا توجد مشاكل مرصودة في هذا المحور.\n")
                else:
                    for issue in self.results[key][:10]: # Limit to top 10 per axis
                        f.write(f"- ⚠️ {issue}\n")
                    if len(self.results[key]) > 10:
                        f.write(f"  *...و {len(self.results[key]) - 10} مشاكل إضافية.*\n")
                f.write("\n")

            f.write("---\n*Generated by AETHER-ZENITH Distillation Engine — Continuous Quality Active.*")

if __name__ == "__main__":
    auditor = DistilledAuditor()
    auditor.scan_project()
    auditor.generate_report()
    print(f"Distilled Audit Complete. Report saved to: {REPORT_PATH}")
