import os
import subprocess
import json
import datetime
import time
import shutil
import re

# --- AETHER-ZENITH V15.0-OMEGA (AUTO-PILOT) CONFIGURATION ---
PROJECT_ROOT = r"c:\tools\workspace\AgriAsset_YECO_Enterprise_Final2"
BACKEND_DIR = os.path.join(PROJECT_ROOT, "backend")
LEDGER_PATH = r"c:\tools\workspace\TheSource\.agents\memory\shadow_ledger.jsonl"
STATUS_PAGE = r"c:\tools\workspace\AgriAsset_YECO_Enterprise_Final2\SYSTEM_HEALTH_LIVE.md"
BRIDGE_PATH = r"c:\tools\workspace\TheSource\.agents\memory\telepathy\bridge.json"
LOCKDOWN_FILE = os.path.join(PROJECT_ROOT, "SYSTEM_LOCKDOWN_ACTIVE")

# Security Sensitivity
CRITICAL_FILES = [
    os.path.join(BACKEND_DIR, "manage.py"),
    os.path.join(BACKEND_DIR, "smart_agri", "settings.py"),
    BRIDGE_PATH
]

def log_event(event_type, message, status="INFO"):
    entry = {
        "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
        "type": f"OMEGA_SENTINEL_{event_type}",
        "status": status,
        "message": message,
        "sovereign_version": "15.0-Omega-AutoPilot"
    }
    with open(LEDGER_PATH, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")

def activate_killswitch(reason):
    """Sovereign Killswitch: Locks the system down."""
    if not os.path.exists(LOCKDOWN_FILE):
        with open(LOCKDOWN_FILE, "w", encoding="utf-8") as f:
            f.write(f"LOCKDOWN INITIATED AT {datetime.datetime.now()}\nREASON: {reason}\n")
        
        # Protective Action: Rename .env to prevent leak continuation
        env_path = os.path.join(PROJECT_ROOT, ".env")
        if os.path.exists(env_path):
            try:
                shutil.move(env_path, env_path + ".LOCKDOWN")
            except:
                pass
            
        log_event("KILLSWITCH_ACTIVATED", f"System locked due to: {reason}", "CRITICAL")
        return True
    return False

def run_cmd(cmd, cwd=None):
    start = time.time()
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=cwd)
        latency = (time.time() - start) * 1000
        return result.returncode, result.stdout, result.stderr, latency
    except Exception as e:
        return -1, "", str(e), 0

def native_secret_search(root_path):
    """Deep Python-native search for secrets to avoid platform dependency (Grep)."""
    leaks = []
    pattern = re.compile(r"sk-[A-Za-z0-9]{20,}")
    for root, dirs, files in os.walk(root_path):
        if ".git" in root or ".venv" in root: continue
        for file in files:
            if file.endswith((".py", ".env", ".txt", ".js", ".json")):
                f_path = os.path.join(root, file)
                try:
                    with open(f_path, "r", encoding="utf-8", errors="ignore") as f:
                        content = f.read()
                        if pattern.search(content):
                            leaks.append(f_path)
                except:
                    pass
    return leaks

def update_dashboard(checks, overall_score, autopilot_active=True):
    lock_status = "🔴 LOCKED" if os.path.exists(LOCKDOWN_FILE) else "🟢 UNLOCKED"
    
    with open(STATUS_PAGE, "w", encoding="utf-8") as f:
        f.write("# 🛡️ Sovereign Sentinel V15.0-Omega (Auto-Pilot)\n")
        f.write(f"> **الحالة السيادية**: 🛡️ OMEGA-AUTOPILOT {'ACTIVE' if autopilot_active else 'STANDBY'}\n")
        f.write(f"> **حالة القفل السياسي (Killswitch)**: {lock_status} | **التقييم**: {overall_score}/100\n")
        f.write(f"> **آخر نبض (Last Pulse):** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        f.write("## 📊 مصفوفة الأمان والنزاهة (Security Matrix)\n")
        f.write("| المحور | الحالة | الإجراء التلقائي |\n")
        f.write("| :--- | :---: | :--- |\n")
        for check, status, action in checks:
            f.write(f"| {check} | {status} | {action} |\n")
        
        f.write("\n## 🧬 معمارية أوميجا (Omega Architecture)\n")
        f.write("```mermaid\ngraph TD\n")
        f.write("  A[Sentinel Omega] --> B{Threat Detected?}\n")
        f.write("  B -- Yes (Secrets/Breach) --> C[Activate Killswitch]\n")
        f.write("  C --> D[Rename .env]\n")
        f.write("  C --> E[Create LOCKDOWN Flag]\n")
        f.write("  B -- No --> F[Maintain Stealth Watch]\n")
        f.write("```\n\n")
        
        f.write("## 🛡️ حالة الحصانة (Immunity Status)\n")
        if os.path.exists(LOCKDOWN_FILE):
            f.write("> [!CAUTION]\n")
            f.write("> **تم تفعيل القفل القسري!** النظام محمي حالياً من أي تسريب. يتطلب فك القفل تدخل بشري سيادي لفتح الملف `SYSTEM_LOCKDOWN_ACTIVE` وإصلاح الثغرة.\n")
        else:
            f.write("> [!TIP]\n")
            f.write("> الطيار الآلي يعمل في وضع الحماية النشطة. أي تسريب للأسرار سيؤدي لإغلاق النظام فوراً.\n")

        f.write("\n--- \n*Generated by AETHER-ZENITH Sentinel Omega — Auto-Pilot Enabled.*")

def main():
    checks = []
    score = 100
    autopilot_active = True
    
    # 1. Native Secret Search (Auto-Pilot Trigger)
    leaks = native_secret_search(PROJECT_ROOT)
    if leaks and autopilot_active:
        activate_killswitch(f"Secret Key detected in: {leaks[0]}")
        checks.append(("Secret Leak", "🛑 BREACH", f"KILLSWITCH ACTIVATED (Found in {os.path.basename(leaks[0])})"))
        score = 0
    else:
        checks.append(("Secret Leak", "✅ SECURE", "Monitoring..."))

    # 2. Critical File Integrity
    for f_path in CRITICAL_FILES:
        if not os.path.exists(f_path):
            activate_killswitch(f"Critical file missing: {os.path.basename(f_path)}")
            checks.append(("File Integrity", "🛑 TAMPERED", "LOCKDOWN"))
            score = 0
            break
    else:
        checks.append(("File Integrity", "✅ INTACT", "Watchdog active"))

    # 3. GRP Fiscal Audit (Simplified check)
    code, out, err, lat = run_cmd('findstr /S "FloatField" backend\\smart_agri\\*.py', cwd=PROJECT_ROOT)
    if "models.py" in out:
        checks.append(("GRP Precision", "⚠️ WARN", "Refactor needed"))
        score -= 10
    else:
        checks.append(("GRP Precision", "✅ ATOMIC", "Compliant"))

    # 4. Migration Healing
    code, out, err, lat = run_cmd("python manage.py showmigrations", cwd=BACKEND_DIR)
    if "[ ]" in out:
        h_code, h_out, h_err, h_lat = run_cmd("python manage.py migrate", cwd=BACKEND_DIR)
        checks.append(("DB Migrations", "🔄 HEALED", "Auto-fix applied"))
    else:
        checks.append(("DB Migrations", "✅ SYNCED", "Clean"))

    # Update Dashboard
    update_dashboard(checks, score, autopilot_active)
    print(f"Sentinel Omega Pulse: {score}/100 (Lockdown: {os.path.exists(LOCKDOWN_FILE)})")

if __name__ == "__main__":
    main()
