/**
 * Sovereign Labs - Live MCP Orchestrator
 * Connects directly to the running `mcp_bridge_server.js` via JSON-RPC over stdio
 * and triggers the CognitiveRouter (Level 5 Autonomy) to mobilize specialized agents.
 */

const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

const MCP_SERVER_PATH = path.join(__dirname, '..', 'mcp_bridge_server.js');
const TARGET_DIR = path.join(__dirname, '..', 'Chess_Engine2');

console.log('🚀 [Sovereign Orchestrator] Starting MCP Server Bridge...');

const mcpProcess = spawn('node', [MCP_SERVER_PATH], {
    cwd: path.join(__dirname, '..'),
    env: Object.assign({}, process.env, { SIMULATION_DRY_RUN: 'false', LIVE_EDIT_MODE: 'true' })
});

let requestSent = false;
let responseBuffer = '';

mcpProcess.stderr.on('data', (data) => {
    const output = data.toString();
    // Only log actual errors, ignore diagnostic INFO from MCP
    if (output.includes('Error') || output.includes('Failed')) {
        console.error('❌ [MCP Server Error]:', output);
    }
    
    // Once the bridge is active, send the request
    if (output.includes('Sovereign stdio MCP bridge active') && !requestSent) {
        console.log('✅ [Sovereign Orchestrator] MCP Server is active. Sending CognitiveRouter Swarm Handoff...');
        
        const rpcCall = {
            jsonrpc: "2.0",
            id: 1,
            method: "tools/call",
            params: {
                name: "nexus_CognitiveRouter",
                arguments: {
                    intent: `قم باستدعاء الوكلاء المتخصصين (ui-synthesizer و react-surgeon) لبناء لعبة الشطرنج في مسار ${TARGET_DIR} فوراً. يجب كتابة الكود كاملاً وتطبيقه.`
                }
            }
        };

        mcpProcess.stdin.write(JSON.stringify(rpcCall) + '\n');
        requestSent = true;
    }
});

mcpProcess.stdout.on('data', (data) => {
    const output = data.toString();
    responseBuffer += output;
    
    // Capture the JSON-RPC response
    if (responseBuffer.includes('"jsonrpc"')) {
        try {
            // Find the json line
            const lines = responseBuffer.split('\n');
            const jsonLine = lines.find(l => l.trim().startsWith('{"jsonrpc"'));
            if (jsonLine) {
                const response = JSON.parse(jsonLine);
                console.log('\n🧠 [MCP Server Response]:');
                console.log(JSON.stringify(response.result || response.error, null, 2));
                
                // Keep alive for 5 seconds to let async agents finish writing files
                console.log('\n⏳ [Sovereign Orchestrator] Waiting 5 seconds for Swarm Agents to finalize physical writes...');
                setTimeout(() => {
                    mcpProcess.kill();
                    verifyOutput();
                }, 5000);
            }
        } catch(e) {}
    }
});

mcpProcess.on('close', (code) => {
    console.log(`\n🛑 [Sovereign Orchestrator] Process exited with code ${code}`);
});

function verifyOutput() {
    console.log('\n🔍 [Sovereign Orchestrator] Verifying outputs at:', TARGET_DIR);
    if (fs.existsSync(TARGET_DIR)) {
        const files = fs.readdirSync(TARGET_DIR);
        console.log('✅ Swarm successfully created directory!');
        console.log('📄 Files generated by agents:', files.join(', '));
    } else {
        console.log('⚠️ Directory not found. Swarm may have encountered an LLM API Key restriction.');
        console.log('⚠️ Please ensure SILICONFLOW_API_KEY or OPENROUTER_KEYS are populated in .env');
    }
}
